void*	emalloc(ulong);
void	init(void);
void	initmap(void);
int	mhdist(int, int, int, int);
void	startsim(void);
void	readfs(void);
void	initdrw(void);
void	resetdraw(void);
void	updatedraw(void);
void	flushfb(void);
void	mouseselect(Point);
int	min(int, int);
int	max(int, int);
