void*	emalloc(ulong);
void	init(void);
void	initmap(void);
int	mhdist(int, int, int, int);
Point	tile2xy(Tile*);
Point	s2p(Point);
Tile*	p2t(Point);
Tile*	s2t(Point);
void	startsim(void);
void	spawn(Tile*, int);
void	readfs(void);
void	initdrw(void);
void	resetdraw(void);
void	updatedraw(int);
void	flushfb(void);
void	drawbuildmenu(void);
void	mouseselect(Point);
void	actionmenu(Point);
void	deselect(void);
void	gsetcursor(int);
int	min(int, int);
int	max(int, int);
int	couldbuild(Building*);
Menuptr	buildmenu(Tile*);
int	isbuildable(Tile*);
